apiVersion: v0
kind: HiveConfig
spec:
  configuration:
    project: devops
    maintainer: tdeheurles@gmail.com

    docker:
      image: deployer
      base: golang
    version:
      major: 0
      minor: 0
    volumes:
      aws: deployer_aws
      ssl: deployer_ssl
    folders:
      aws: "/root/.aws"
      ssl: "/root/.ssl"
