#!/usr/bin/env bash

exitCode=0

if [ "${build}" == "" ];then
    build=0
fi

echo -e "\n\e[34mBUILD AND TEST\e[0m"
./hive do build devops deployer build ${build}
if [ $? != 0 ];then exitCode=1; fi

if [ ${exitCode} == 0 ];then
    echo -e "\n\e[34mRUN\e[0m"
    docker run \
        --rm \
        --net=host \
        -v deployer_aws:/root/.aws \
        -v deployer_ssl:/root/ssl \
        deployer:0.0 $@
    if [ $? == 1 ];then exitCode=1; fi
fi

color="32"
if [ ${exitCode} != 0 ];then
    color="31"
fi
echo -e "\n\e[${color}mExit code: ${exitCode}\e[0m"
exit ${exitCode}
